### ISSUE TITLE
0.24.0-dev.95 only works with release builds

### ISSUE THREAD

**Issue by mrlacey** [unoplatform/uno.ui.runtimetests.engine#152]
## Current behavior

For a solution using 0.24.0-dev.95 Any test project that references another project, it looks for a NuGet package source in a path relative to the referenced project and in a `\Release` directory.

## Expected behavior

It should not do anything dependeny on the type of build.
I should be able to build test projects and execute tests in debug mode without first having to do a local release build!

## How to reproduce it (as minimally and precisely as possible)

- Create a test project using v0.24.0-dev.95 of the library
- Reference another project in the solution.
- Make sure in DEBUG mode
- Try and build the test project (or the whole solution)
- Get an exception like `Error	NU1301	The local source 'C:\[PATH TO REFERENCED PROJECT]\Release' doesn't exist.`

**Internal Uno project available for repro/test if needed.**

## Environment

Nuget Package:

Uno.UI.RuntimeTests.Engine

Package Version(s):

0.24.0-dev.95

Affected platform(s):

- [x] Testing
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [x] 2022 (17.9.0 Preview 1)

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Did this happen because any CI checks run as Release but developers often work in Debug mode and build and run tests in this mode?

**Comment by dr1rrb** [comment]
Hummmm ... weird, contacted you in private for the repro :)

**Comment by mrlacey** [comment]
Trying different versions. **The last version that works is 0.19.0-dev.82**

**Comment by dr1rrb** [comment]
Ok so I tried with your project and indeed I got some package restore issue :

```
error NU1507: Warning As Error: There are 2 package sources defined in your configuration. When using central package management, please map your package sources with package source mapping (https://aka.ms/nuget-package-source-mapping) or specify a single package source. The following sources are defined: nuget.org, Unoplatform stagging
```

Disabling the "Uno staging" nuget feed in VS settings fixed the issue on my side.

The weird thing is that this the `Uno.UI.RuntimeTests.Engine` package is not even present on the "staging feed" and it doesn't have any dependency :/

**Comment by dr1rrb** [comment]
So according to @jeromelaban, you should only ignore (nowarn) NU1507 in your project / solution

**Comment by mrlacey** [comment]
So, I'm going to assume a NuGet-related issue that somehow only happens when using the package. :/
