### ISSUE TITLE
Error compiling with Uno.Sdk SingleProject + Uno.UI.RuntimeTests.Engine on WinUI.

### ISSUE THREAD

**Issue by ADD-David-Antolin** [unoplatform/uno.ui.runtimetests.engine#173]
## Current behavior

A project with Uno.Sdk + Uno.UI.RuntimeTests.Engine does not compile for WinUI. 

## Expected behavior

A project with Uno.Sdk + Uno.UI.RuntimeTests.Engine compiles for all targets.

## How to reproduce it (as minimally and precisely as possible)

[RuntimeTestEngineBug.zip](https://github.com/unoplatform/uno.ui.runtimetests.engine/files/15119430/RuntimeTestEngineBug.zip)

Open the repro project and compile UnoApp1. The following errors should appear:

CS0234: The type or namespace name 'Messages' does not exist in the namespace 'Uno.UI.RemoteControl.HotReload' (are you missing an assembly reference?
CS0246: The type or namespace name 'UpdateFile' could not be found (are you missing an assembly reference?

## Environment

Nuget Package:

Uno.WinUI 5.2.95
Uno.WinUI.DevServer 5.2.95
Uno.RuntimeTests.Engine 0.36.0-dev.124

Affected platform(s):
- [x] Windows

Visual Studio:

- [x] 2022 17.9.6

## Anything else we need to know?

The problem seems to be that now `Uno.WinUI.DevServer` is applied to WinUI target framework by `Uno.Sdk`, but the WinUI version of DevServer does not have neither the dependency to `Uno.WinUI.DevServer.Messaging` nor access to the class `UpdateFile`.

**Comment by jeromelaban** [comment]
Thanks. We'll be fixing this in Uno.Sdk, though in the meantime you should be able to add an explicit package reference to `Uno.WinUI.DevServer.Messaging` to get you going.

**Comment by ADD-David-Antolin** [comment]
@jeromelaban I did that but still does not find the class `UpdateFile`.

**Comment by ADD-David-Antolin** [comment]
@Jen-Uno yes, it is solved.
