### ISSUE TITLE
Build failure in release mode.

### ISSUE THREAD

**Issue by ADD-Eugenio-Lopez** [unoplatform/uno.ui.runtimetests.engine#179]
## Current behavior

In a RuntimeTest project using the version 5.5.43 of Uno.Sdk in Release mode, some errors occur while compiling and does not compile.

## Expected behavior

It compiles correctly.

## How to reproduce it 
[RuntimeTestsFailCompile.zip](https://github.com/user-attachments/files/17751481/RuntimeTestsFailCompile.zip)
Open the attached project, set Release mode and compile it.

## Environment

Nuget Package:
 Uno.Sdk
Uno.UI.Runtimetests.engine

Package Version(s):
Uno.Sdk 5.5.43
Uno.UI.Runtimetests.engine 

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [X] Build tasks

Visual Studio:

- [X] 2022 (version: 17.11.5)

Relevant plugins:

## Anything else we need to know?

**Comment by jeromelaban** [comment]
The fix is available in 1.33.0-dev.11.
