### ISSUE TITLE
included test app crashes on windows.

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno.ui.runtimetests.engine#58]
## Current behavior
src/Uno.UI.RuntimeTests.Engine/Uno.UI.RuntimeTests.Engine.Windows/Uno.UI.RuntimeTests.Engine.Windows.csproj
throws an exception on launch:
```
System.DllNotFoundException: 'Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)'
	at Uno.UI.RuntimeTests.Engine.Windows.dll!Uno.UI.RuntimeTests.Engine.Program.Main(string[] args = {string[0]}) Line 28	C#
```

## Expected behavior
^ should not crash

## Anything else we need to know?
Under the winui "PROJECT_NAME.Windows" head directory, there is a folder named "Properties" which is missing in this repo, and .gitignore-ed.
It is normally present when you create a new project. If you add it back, the app will launch without exception.

said folder: https://github.com/unoplatform/uno/tree/4.6.19/src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/WinUI/Properties

**Comment by jeromelaban** [comment]
Ah yes, this one is a .gitignore issue, where those files are ignored by default and are missing when included in the repo. I'll push those files.
