### ISSUE TITLE
Tests are run twice.

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno.ui.runtimetests.engine#60]
when using a separate assembly for tests and said assembly name ends with "tests", 
the tests are run twice.

```cs
var testAssembliesTypes =
	from asm in AppDomain.CurrentDomain.GetAssemblies()
	where asm.GetName()?.Name?.EndsWith("tests", StringComparison.OrdinalIgnoreCase) ?? false
	from type in asm.GetTypes()
	select type;

var types = GetType().GetTypeInfo().Assembly.GetTypes().Concat(testAssembliesTypes);
```
^ `AppDomain.CurrentDomain.GetAssemblies()` definitely contains `GetType().GetTypeInfo().Assembly.GetTypes()`

**Comment by Xiaoy312** [comment]
```cs
		var testAssemblies = AppDomain.CurrentDomain.GetAssemblies()
			.Where(x => x.GetName()?.Name?.EndsWith("Tests", StringComparison.OrdinalIgnoreCase) ?? false)
			.Concat(new[] { GetType().GetTypeInfo().Assembly })
			.Distinct();
		var types = testAssemblies.SelectMany(x => x.GetTypes());
```

**Comment by jeromelaban** [comment]
Interesting, this would mean we have a similar issue inside of Uno.UI.

**Comment by Xiaoy312** [comment]
In uno.ui, this is avoided because the UnitTestsControl is in the SampleApps, so the `GetType().GetTypeInfo().Assembly` there contains nothing. And, the tests are in Uno.UI.RuntimeTests (separate assembly).
So there is no double inclusion there.

**Comment by jeromelaban** [comment]
Makes sense!
